check_f2fs: fix build error in abfarm474
This patch fixes this build error:

error: comparison of integers of different signs: 'long long' and 'unsigned long long' [-Werror,-Wsign-compare]

if (sb.st_size / 512 != sb.st_blocks) {
~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~
1 error generated.

Bug: 77146255
Bug: 77344057
Change-Id: I0ba0328fd81f4042684563c8472f100ef614643d
Fixes: 160ec1fef58d ("check_f2fs: test wrong write(2) call")
Signed-off-by: Jaegeuk Kim <jaegeuk@google.com>